sudo: false
language: python

python:
  - "2.6"
  - "2.7"

install:
    - pip install prettytable
    - pip install pytz
    - pip install datetime
    - pip install tqdm
    - pip install coloredlogs
    - pip install requests
    - pip install nose
    - pip install pep8
    - pip install tox
script:
    - pep8 --max-line-length=180
    - nosetests -s
    
deploy:
  provider: pypi
  user: "lewzylu"
  password:
    secure: "VHI0VQJ96KP73KSk6Jdlvk/OQiXcZ4wkSb/qK/O9sHQIbgz7cXB7NHM53nEJL7Fie2QnPZuO5//ZbbyfrgWpkqKazIlL3ahQwRsdsiJC0teeBWzZ5mNPfDMaNn/YHD5Hb5e3nOgEapnyY80WyldFY/wWkbJOP/49XIR51707Bcr+uXPR39GOr3GdLDsUkzp7LK8wXqIzAKY2cnfxE8CJBAutlFBB43vhPMb/zfiacijATPDVQ5q0drLHR6Fw22QtIk8ebO/eeSBOUirnwtwANng/Y9z8hbmOzJauvWJTDw59EUkzKX22Gc3TLJL4U14Wtnhvt845Jkt5x0dqELQnGSGnNetzBMQbrRAxuFp6UdlNF9UcY/fE2FfXLSz1kvhcZmFEWxnAaKfi+JQ0aCKxvwpIvcRv3rVfBZ3ZEwNuW9k+PItFirhp5aOS5Mutvi1YAEwkfbbXSIwczLUfSNLCIIisfwB4LSFTDKnv8mK3Aq+C1NosC4QJ29g4voOrBog9RpNe3+qyQxJWkWEU9WeTOSx8TPgp+5mraYGvK8xVIJjcJoXmc6BFobdUJWj2a3YdVBDkR6iiSusenqa2ArHC1r14HHL7/2fIxXYZu7ewAmwaMyq7iFz+d0MVYYvtPQExHu/63pv0za8dbSh3HvGXTpzUTeN829BZOzODC4SdDe4="
